[workspace]
changelog_update = true
git_release_enable = true
publish = false
semver_check = false

[[package]]
name = "taskfast-cli"
changelog_include = ["taskfast-cli"]

[[package]]
name = "taskfast-agent"
release = false

[[package]]
name = "taskfast-client"
release = false

[[package]]
name = "taskfast-chains"
release = false
