[workspace]
changelog_update = true
git_release_enable = false
publish = true
semver_check = true

[[package]]
name = "taskfast-cli"
publish = true
changelog_include = ["taskfast-cli"]

[[package]]
name = "taskfast-agent"
publish = false
release = false

[[package]]
name = "taskfast-client"
publish = false
release = false

[[package]]
name = "taskfast-chains"
publish = false
release = false
