[files]
extend-exclude = [
    "target/",
    "Cargo.lock",
    "*.lock",
    ".git/",
]

[default.extend-identifiers]
"am-iit" = "am-iit"
"unparseable" = "unparseable"

[default.extend-words]
iit = "iit"
unparseable = "unparseable"
