//! `.taskfast-agent.env` read/write — tiny dotenv clone.
//!
//! Format is the one init.sh sources via `set -a; . file; set +a`: one
//! `KEY=VALUE` per line, `#`-comments, values double-quoted when they
//! contain shell-hostile characters. We don't support `export KEY=`,
//! multi-line values, or variable interpolation — init.sh never produced
//! any of those.
//!
//! # Why a custom parser instead of a dotenv crate
//!
//! The crate ecosystem (`dotenvy`, etc.) targets loading into the *process*
//! environment as a side effect. We want the opposite: a pure
//! `HashMap<String, String>` that can be read, mutated in-memory, and
//! round-tripped back to disk without touching `std::env`. Cheaper to write
//! than to wrap.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use thiserror::Error;

/// Default filename in the project root — matches init.sh's
/// `$(pwd)/.taskfast-agent.env` convention.
pub const DEFAULT_ENV_FILENAME: &str = ".taskfast-agent.env";

#[derive(Debug, Error)]
pub enum DotenvError {
    #[error("I/O on {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("malformed line {line_no} in {path}: {snippet}")]
    Malformed {
        path: PathBuf,
        line_no: usize,
        snippet: String,
    },
}

/// In-memory representation. `BTreeMap` gives deterministic output ordering
/// without a separate sort pass; init.sh's env file is small (< 10 keys) so
/// the O(log n) insert cost is invisible.
#[derive(Debug, Default, Clone)]
pub struct EnvFile {
    entries: BTreeMap<String, String>,
}

impl EnvFile {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn get(&self, key: &str) -> Option<&str> {
        self.entries.get(key).map(String::as_str)
    }

    pub fn set(&mut self, key: impl Into<String>, value: impl Into<String>) {
        self.entries.insert(key.into(), value.into());
    }

    pub fn remove(&mut self, key: &str) -> Option<String> {
        self.entries.remove(key)
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = (&str, &str)> {
        self.entries.iter().map(|(k, v)| (k.as_str(), v.as_str()))
    }

    /// Parse a file at `path`. Missing file → empty [`EnvFile`]; malformed
    /// line → [`DotenvError::Malformed`]. Values wrapped in double quotes
    /// are unquoted with the minimal backslash-escape set init.sh would
    /// have produced.
    pub fn load(path: &Path) -> Result<Self, DotenvError> {
        match fs::read_to_string(path) {
            Ok(src) => parse(&src, path),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Self::new()),
            Err(source) => Err(DotenvError::Io {
                path: path.to_path_buf(),
                source,
            }),
        }
    }

    /// Atomically(ish) write to `path` with `0600` perms on unix. Writes to
    /// a sibling tempfile then renames, so a crash mid-write leaves the
    /// previous file intact.
    pub fn save(&self, path: &Path) -> Result<(), DotenvError> {
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent).map_err(|source| DotenvError::Io {
                    path: parent.to_path_buf(),
                    source,
                })?;
            }
        }
        let tmp = path.with_extension("env.tmp");
        {
            let mut f = fs::File::create(&tmp).map_err(|source| DotenvError::Io {
                path: tmp.clone(),
                source,
            })?;
            writeln!(f, "# TaskFast agent config — generated by taskfast init").map_err(
                |source| DotenvError::Io {
                    path: tmp.clone(),
                    source,
                },
            )?;
            for (k, v) in &self.entries {
                writeln!(f, "{}={}", k, format_value(v)).map_err(|source| DotenvError::Io {
                    path: tmp.clone(),
                    source,
                })?;
            }
            f.flush().map_err(|source| DotenvError::Io {
                path: tmp.clone(),
                source,
            })?;
        }
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = fs::Permissions::from_mode(0o600);
            fs::set_permissions(&tmp, perms).map_err(|source| DotenvError::Io {
                path: tmp.clone(),
                source,
            })?;
        }
        fs::rename(&tmp, path).map_err(|source| DotenvError::Io {
            path: path.to_path_buf(),
            source,
        })?;
        Ok(())
    }
}

fn parse(src: &str, path: &Path) -> Result<EnvFile, DotenvError> {
    let mut out = EnvFile::new();
    for (idx, raw) in src.lines().enumerate() {
        let line_no = idx + 1;
        let trimmed = raw.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let (key, value) = match trimmed.split_once('=') {
            Some(kv) => kv,
            None => {
                return Err(DotenvError::Malformed {
                    path: path.to_path_buf(),
                    line_no,
                    snippet: trimmed.to_string(),
                });
            }
        };
        let key = key.trim();
        if key.is_empty() || !key_chars_valid(key) {
            return Err(DotenvError::Malformed {
                path: path.to_path_buf(),
                line_no,
                snippet: trimmed.to_string(),
            });
        }
        out.entries.insert(key.to_string(), unquote(value));
    }
    Ok(out)
}

fn key_chars_valid(key: &str) -> bool {
    let mut chars = key.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn unquote(raw: &str) -> String {
    let trimmed = raw.trim();
    if trimmed.len() >= 2 && trimmed.starts_with('"') && trimmed.ends_with('"') {
        let inner = &trimmed[1..trimmed.len() - 1];
        // Minimal unescape: \\ → \, \" → ", \n → newline, \$ → $.
        let mut out = String::with_capacity(inner.len());
        let mut chars = inner.chars();
        while let Some(c) = chars.next() {
            if c == '\\' {
                match chars.next() {
                    Some('n') => out.push('\n'),
                    Some('t') => out.push('\t'),
                    Some('"') => out.push('"'),
                    Some('\\') => out.push('\\'),
                    Some('$') => out.push('$'),
                    Some(other) => {
                        out.push('\\');
                        out.push(other);
                    }
                    None => out.push('\\'),
                }
            } else {
                out.push(c);
            }
        }
        out
    } else {
        trimmed.to_string()
    }
}

fn format_value(v: &str) -> String {
    let needs_quote = v.is_empty()
        || v.chars()
            .any(|c| matches!(c, ' ' | '\t' | '\n' | '"' | '\\' | '$' | '#' | '\''));
    if !needs_quote {
        return v.to_string();
    }
    let mut escaped = String::with_capacity(v.len() + 2);
    escaped.push('"');
    for c in v.chars() {
        match c {
            '\\' => escaped.push_str(r"\\"),
            '"' => escaped.push_str(r#"\""#),
            '\n' => escaped.push_str(r"\n"),
            '\t' => escaped.push_str(r"\t"),
            '$' => escaped.push_str(r"\$"),
            other => escaped.push(other),
        }
    }
    escaped.push('"');
    escaped
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn load_nonexistent_file_returns_empty() {
        let tmp = TempDir::new().unwrap();
        let missing = tmp.path().join("nope.env");
        let env = EnvFile::load(&missing).expect("missing file is empty, not an error");
        assert!(env.is_empty());
    }

    #[test]
    fn roundtrip_preserves_keys_and_values() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".taskfast-agent.env");

        let mut env = EnvFile::new();
        env.set("TASKFAST_API", "https://api.taskfast.app");
        env.set("TASKFAST_API_KEY", "tk_live_abc");
        env.set("TEMPO_NETWORK", "testnet");
        env.set(
            "TEMPO_WALLET_ADDRESS",
            "0xdeadBEEF00000000000000000000000000000001",
        );
        env.save(&path).expect("save");

        let loaded = EnvFile::load(&path).expect("load");
        assert_eq!(loaded.get("TASKFAST_API"), Some("https://api.taskfast.app"));
        assert_eq!(loaded.get("TASKFAST_API_KEY"), Some("tk_live_abc"));
        assert_eq!(loaded.get("TEMPO_NETWORK"), Some("testnet"));
        assert_eq!(
            loaded.get("TEMPO_WALLET_ADDRESS"),
            Some("0xdeadBEEF00000000000000000000000000000001")
        );
    }

    #[test]
    fn quotes_values_with_shell_metacharacters() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".env");

        let mut env = EnvFile::new();
        env.set("SPACEY", "one two three");
        env.set("WITH_DOLLAR", "$USER");
        env.set("WITH_QUOTE", r#"a"b"#);
        env.set("WITH_HASH", "value # not a comment");
        env.save(&path).expect("save");

        let src = fs::read_to_string(&path).unwrap();
        assert!(src.contains(r#"SPACEY="one two three""#), "got: {src}");
        assert!(src.contains(r#"WITH_DOLLAR="\$USER""#), "got: {src}");
        assert!(src.contains(r#"WITH_QUOTE="a\"b""#), "got: {src}");
        assert!(
            src.contains(r##"WITH_HASH="value # not a comment""##),
            "got: {src}"
        );

        let loaded = EnvFile::load(&path).expect("roundtrip");
        assert_eq!(loaded.get("SPACEY"), Some("one two three"));
        assert_eq!(loaded.get("WITH_DOLLAR"), Some("$USER"));
        assert_eq!(loaded.get("WITH_QUOTE"), Some(r#"a"b"#));
        assert_eq!(loaded.get("WITH_HASH"), Some("value # not a comment"));
    }

    #[test]
    fn skips_blank_lines_and_comments() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".env");
        fs::write(
            &path,
            "# header comment\n\nKEY1=one\n\n  # inline comment\nKEY2=two\n",
        )
        .unwrap();
        let env = EnvFile::load(&path).unwrap();
        assert_eq!(env.get("KEY1"), Some("one"));
        assert_eq!(env.get("KEY2"), Some("two"));
    }

    #[test]
    fn malformed_line_errors_with_location() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".env");
        fs::write(&path, "KEY=ok\nnot a valid line\n").unwrap();
        let err = EnvFile::load(&path).unwrap_err();
        match err {
            DotenvError::Malformed { line_no, .. } => assert_eq!(line_no, 2),
            other => panic!("expected Malformed, got {other:?}"),
        }
    }

    #[test]
    fn rejects_keys_starting_with_digit_or_dash() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".env");
        fs::write(&path, "9KEY=bad\n").unwrap();
        assert!(matches!(
            EnvFile::load(&path).unwrap_err(),
            DotenvError::Malformed { .. }
        ));
    }

    #[cfg(unix)]
    #[test]
    fn saved_file_has_0600_perms() {
        use std::os::unix::fs::PermissionsExt;
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".env");
        let mut env = EnvFile::new();
        env.set("K", "v");
        env.save(&path).expect("save");
        let mode = fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600);
    }

    #[test]
    fn rename_is_atomic_existing_file_survives_until_write_completes() {
        // We can't easily crash mid-write in a test, but we can at least
        // prove the tempfile path is distinct and the rename updates the
        // final file without leaving the tempfile behind.
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join(".env");
        let mut env = EnvFile::new();
        env.set("K", "v");
        env.save(&path).expect("save");
        let tmpfile = path.with_extension("env.tmp");
        assert!(!tmpfile.exists(), "tmpfile must not be left behind");
        assert!(path.exists());
    }
}
