name: Release-plz

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main]

jobs:
  release-plz:
    name: release-plz
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}

      - uses: dtolnay/rust-toolchain@stable

      - name: Release-plz (release + PR)
        uses: release-plz/action@395042a06223c60c3e953d5fa124e97dfef96672 # v0.5.87
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
